# MLflow 설정
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "civil-complaint"
  artifact_location: "./mlruns"

  autolog:
    log_models: true
    log_input_examples: true
    log_model_signatures: true
